version: '3.8'

services:
  postgres:
    image: postgres:16.0-alpine3.18
    container_name: studdy-buddy-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: studdy_buddy
